-- 코드를 입력하세요
SELECT A.CART_ID
FROM CART_PRODUCTS A JOIN CART_PRODUCTS B ON A.CART_ID = B.CART_ID
WHERE (A.NAME = 'Milk' AND B.NAME = 'Yogurt') OR (A.NAME = 'Yogurt' AND B.NAME = 'Milk') 
GROUP BY A.CART_ID
ORDER BY A.CART_ID